---
- name: "Human"
  description: "A humanoid creature from the Star Wars universe"
  generate: 
    - sql
    - graphql
    - protobuf
  graphql:
    package: "resolvers"
  sql:
    table: "humans"
    dialect: "postgres"
  fields: 
    - name: "id"
      internal: "id"
      description: "The ID of the human"
      deprecated: false
      type: ID
      indexes: 
        - primary
    - name: "name"
      internal: "name"
      description: "What this human calls themselves"
      deprecated: false
      type: string
      indexes:
         - name_index
         - name_height_index
    - name: "height"
      internal: "height"
      description: "Height in the preferred unit, default is meters"
      deprecated: false
      type: string
      indexes:
          - name_height_index
    - name: "mass"
      internal: "mass"
      description: "Mass in kilograms, or null if unknown"
      deprecated: false
      type: string

- name: "Droid"
  description: "An autonomous mechanical character in the Star Wars universe"
  sql:
    table: "droids"
  fields: 
    - name: "id"
      description: "The ID of the human"
      deprecated: false
      type: ID
      indexes:
        - primary
    - name: "name"
      description: "What this human calls themselves"
      deprecated: false
      type: string
      indexes:
         - name_index
    - name: "primary_function"
      description: "This droid's primary function"
      deprecated: false
      type: string
      indexes: 
          - name_index

